### ISSUE TITLE
Is it possible to record opposing team rating as well as or instead of MMR?

### ISSUE THREAD

**Issue by sschepens** [denishamann/ArenaStats#17]
I would like to see recorded opposing team rating and rating change, this is displayed in blizzard scoreboard at the end of arena.

**Comment by Simon3** [comment]
This information is already recorded and available in the export: `enemyOldTeamRating`, `enemyNewTeamRating`. 
Unfortunately, we do not plan on adding it to the in-game table, as we think there is not any room left for it. 
But feel free to open a PR if you think you can do it in a nice way.
